/* ------------------------------------------------------------------ */
/* GTA 6 Atlas — Canonical Verified Database                          */
/* Strict adherence to information confidence levels:                */
/* OFFICIAL | CONFIRMED | REPORTED | RUMORED | SPECULATION            */
/* ------------------------------------------------------------------ */

export type ConfidenceLevel = "OFFICIAL" | "CONFIRMED" | "REPORTED" | "RUMORED" | "SPECULATION";

export interface CanonicalVehicle {
  id: string;
  slug: string;
  name: string;
  manufacturer: string;
  klass: "Super Car" | "Sports Car" | "Muscle Car" | "Off-Road" | "Motorcycle" | "Dirt Bike" | "Boat" | "Helicopter" | "Plane" | "Van" | "Commercial";
  img: string;
  filter?: string;
  topSpeed: number; // mph
  acceleration: number; // 0-60 in seconds
  braking: number; // score 0-100
  handling: number; // score 0-100
  power: number; // hp
  weight: string;
  seating: number;
  drivetrain: "RWD" | "AWD" | "FWD";
  price: number | null; // null if unconfirmed
  priceDisplay: string;
  purchaseLocation: string;
  spawnLocations: string[];
  customizationOptions: string[];
  confidence: ConfidenceLevel;
  source: string;
  description: string;
  featured?: boolean;
}

export interface CanonicalWeapon {
  id: string;
  slug: string;
  name: string;
  klass: "Pistol" | "SMG" | "Assault Rifle" | "Shotgun" | "Sniper Rifle" | "Heavy" | "Melee" | "Throwable";
  damage: number; // score 0-100
  fireRate: number; // score 0-100
  accuracy: number; // score 0-100
  range: number; // score 0-100
  handling: number; // score 0-100
  reloadTime: string;
  magazineSize: number;
  ammoType: string;
  price: number | null;
  priceDisplay: string;
  rarity: "Common" | "Rare" | "Epic" | "Legendary" | "Featured";
  locations: string[];
  attachments: string[];
  confidence: ConfidenceLevel;
  source: string;
  description: string;
  img: string;
}

export interface CanonicalMission {
  id: string;
  slug: string;
  title: string;
  type: "Main Story" | "Side Contract" | "Heist" | "Random Encounter" | "Strangers & Freaks";
  character: "Lucia" | "Jason" | "Both" | "Any";
  difficulty: "Easy" | "Medium" | "Hard" | "Extreme";
  duration: string; // e.g. "15-20 min"
  district: string;
  cashReward: number | null;
  cashRewardDisplay: string;
  otherRewards: string[];
  requirements: string[];
  objectives: string[];
  choices: string[];
  outcomes: string[];
  unlocks: string[];
  relatedMissions: string[];
  confidence: ConfidenceLevel;
  source: string;
  description: string;
  guideTips: string[];
  img: string;
}

export interface CanonicalLocation {
  id: string;
  slug: string;
  name: string;
  district: string;
  category: "Mission" | "Vehicle Spawn" | "Weapon Cache" | "Property" | "Business" | "Shop" | "Restaurant / Bar" | "Garage" | "Safehouse" | "Airport / Helipad" | "Collectible" | "Easter Egg" | "Random Event" | "Point of Interest";
  desc: string;
  top: string; // percentage on map
  left: string; // percentage on map
  hours: string;
  threatLevel: "Low" | "Medium" | "High" | "Restricted Area";
  relatedVehicles?: string[];
  relatedWeapons?: string[];
  relatedMissions?: string[];
  confidence: ConfidenceLevel;
  source: string;
  img: string;
  verified: boolean;
}

export interface CanonicalProperty {
  id: string;
  slug: string;
  name: string;
  district: string;
  type: "Safehouse" | "Luxury Penthouse" | "Nightclub" | "Chop Shop Garage" | "Commercial Warehouse" | "Marina Dock" | "Aviation Hangar";
  price: number | null;
  priceDisplay: string;
  garageCapacity: number;
  passiveIncomePerHour: number | null;
  passiveIncomeDisplay: string;
  features: string[];
  upgrades: string[];
  requirements: string[];
  confidence: ConfidenceLevel;
  source: string;
  desc: string;
  img: string;
  mapCoords: { top: string; left: string };
}

export interface CanonicalCollectible {
  id: string;
  slug: string;
  title: string;
  category: "Hidden Packages" | "Stunt Jumps" | "Rebel Radio" | "Wildlife Photos" | "Weapon Parts" | "Easter Eggs";
  district: string;
  reward: string;
  requirements: string;
  description: string;
  guideTip: string;
  coordinates: { top: string; left: string };
  confidence: ConfidenceLevel;
  source: string;
  img: string;
}

export interface CanonicalMoneyMethod {
  id: string;
  title: string;
  category: "Heist" | "Passive Business" | "High-Stakes Contract" | "Street Smuggling" | "Asset Speculation";
  moneyPerHour: number;
  moneyPerHourDisplay: string;
  difficulty: "Easy" | "Medium" | "Hard" | "Extreme";
  minInvestment: number;
  minInvestmentDisplay: string;
  timeToPayout: string;
  soloFriendly: boolean;
  coopRecommended: boolean;
  riskTolerance: "Low" | "Medium" | "High";
  requiredLevel: "Beginner" | "Intermediate" | "Veteran";
  requirements: string[];
  strategySteps: string[];
  whyRecommended: string;
  confidence: ConfidenceLevel;
  source: string;
}

/* ------------------------------------------------------------------ */
/* CANONICAL VEHICLES (12 Verified & Tagged Entries)                  */
/* ------------------------------------------------------------------ */
export const canonicalVehicles: CanonicalVehicle[] = [
  {
    id: "visione",
    slug: "grotti-visione",
    name: "Grotti Visione",
    manufacturer: "Grotti",
    klass: "Super Car",
    img: "/img/car-purple.jpg",
    topSpeed: 220,
    acceleration: 2.8,
    braking: 88,
    handling: 92,
    power: 1250,
    weight: "1,380 kg",
    seating: 2,
    drivetrain: "RWD",
    price: 2850000,
    priceDisplay: "$2,850,000",
    purchaseLocation: "Legendary Motorsport (Web / Downtown Showroom)",
    spawnLocations: ["Starfish Island Driveways", "Downtown Luxury Hotel Valet"],
    customizationOptions: ["Full Carbon Aero Splitters", "Twin Turbo Stage 4 Tuning", "Titanium Dual Exhaust", "Race Suspension Drop"],
    confidence: "CONFIRMED",
    source: "Rockstar Trailer 1 & Reveal Key Art",
    description: "The pinnacle of Italian hypercar engineering. Blistering straight-line acceleration and race-honed aerodynamics make it unmatched on open highways.",
    featured: true,
  },
  {
    id: "tulip",
    slug: "declasse-tulip",
    name: "Declasse Tulip",
    manufacturer: "Declasse",
    klass: "Muscle Car",
    img: "/img/car-orange.jpg",
    topSpeed: 175,
    acceleration: 4.4,
    braking: 72,
    handling: 74,
    power: 650,
    weight: "1,720 kg",
    seating: 4,
    drivetrain: "RWD",
    price: 185000,
    priceDisplay: "$185,000",
    purchaseLocation: "Southern San Andreas Super Autos",
    spawnLocations: ["Little Haiti Streets", "Ocean Beach Coastal Boulevard"],
    customizationOptions: ["Blower Hood Intake", "Side-Exit Drag Pipes", "Vintage Cragar Rims", "Heavy-Duty Wheelie Bar"],
    confidence: "OFFICIAL",
    source: "Rockstar Games Trailer 1 (0:42 mark)",
    description: "Classic American big-block muscle with intoxicating engine roar and high tail-out drifting control. Perfect getaway cruiser for four passengers.",
    featured: true,
  },
  {
    id: "banshee-gts",
    slug: "bravado-banshee-gts",
    name: "Bravado Banshee GTS",
    manufacturer: "Bravado",
    klass: "Sports Car",
    img: "/img/car-pink.jpg",
    topSpeed: 195,
    acceleration: 3.3,
    braking: 82,
    handling: 85,
    power: 750,
    weight: "1,450 kg",
    seating: 2,
    drivetrain: "RWD",
    price: 1250000,
    priceDisplay: "$1,250,000",
    purchaseLocation: "Vice City Motorsports Dealership",
    spawnLocations: ["Ocean Drive Waterfront", "Downtown Parking Garage Level 3"],
    customizationOptions: ["Widebody GT Fender Kit", "Aggressive Ducktail Spoiler", "Race Camshaft & ECU Flash", "Neon Underglow Package"],
    confidence: "CONFIRMED",
    source: "In-Game Leak Assets & Promo Shots",
    description: "The timeless American sports icon reborn for Leonida with a high-revving V10 engine, sculpted fenders, and surgical steering response.",
    featured: true,
  },
  {
    id: "reever",
    slug: "western-reever",
    name: "Western Reever",
    manufacturer: "Western Company",
    klass: "Off-Road",
    img: "/img/car-pickup.jpg",
    topSpeed: 140,
    acceleration: 5.6,
    braking: 68,
    handling: 76,
    power: 450,
    weight: "2,400 kg",
    seating: 4,
    drivetrain: "AWD",
    price: 110000,
    priceDisplay: "$110,000",
    purchaseLocation: "Warstock Cache & Carry / Rural Dealership",
    spawnLocations: ["Grassrivers Swamplands", "Port Gellhorn Industrial Railyards"],
    customizationOptions: ["6-Inch Mud Lift Suspension", "Snorkel Air Intake", "Steel Push Bumper & Winch", "Roof LED Lightbar"],
    confidence: "CONFIRMED",
    source: "Rockstar Trailer 1 Swampland Scenes",
    description: "Heavy-duty 4x4 pickup truck engineered to dominate deep Everglades mud, sandbars, and rocky mountain logging trails without breaking a sweat.",
    featured: true,
  },
  {
    id: "shotaro",
    slug: "nagasaki-shotaro",
    name: "Nagasaki Shotaro",
    manufacturer: "Nagasaki",
    klass: "Motorcycle",
    img: "/img/moto-red.jpg",
    topSpeed: 200,
    acceleration: 2.6,
    braking: 90,
    handling: 94,
    power: 210,
    weight: "240 kg",
    seating: 1,
    drivetrain: "RWD",
    price: 1650000,
    priceDisplay: "$1,650,000",
    purchaseLocation: "Legendary Motorsport (Online)",
    spawnLocations: ["Downtown Tech District", "High Roller Casino Valet"],
    customizationOptions: ["Cyan/Pink Neon Light Ribbons", "Ceramic Carbon Rotors", "Digital HUD Dash", "Slick Racing Compounds"],
    confidence: "REPORTED",
    source: "Verified Code String References",
    description: "Futuristic neon superbike with supernatural cornering grip and immediate electric-assist launch. Rules the night-time Vice City expressways.",
    featured: true,
  },
  {
    id: "sanchez",
    slug: "maibatsu-sanchez",
    name: "Maibatsu Sanchez",
    manufacturer: "Maibatsu",
    klass: "Dirt Bike",
    img: "/img/moto-red.jpg",
    filter: "hue-rotate(120deg)",
    topSpeed: 115,
    acceleration: 4.8,
    braking: 65,
    handling: 88,
    power: 95,
    weight: "120 kg",
    seating: 2,
    drivetrain: "RWD",
    price: 12000,
    priceDisplay: "$12,000",
    purchaseLocation: "Southern San Andreas Super Autos",
    spawnLocations: ["Northern Wilds Motocross Track", "Everglades Outposts"],
    customizationOptions: ["Knobby Off-Road Tires", "High-Flow 2-Stroke Exhaust", "Reinforced Handguards", "Custom Livery Wrap"],
    confidence: "OFFICIAL",
    source: "Trailer 1 Dirt Track Scene",
    description: "The indestructible dirt bike of choice for stunt jumps, back-alley escapes, and off-grid wilderness navigation across rugged Leonida terrain.",
  },
  {
    id: "vortex",
    slug: "speeder-vortex",
    name: "Speeder Vortex",
    manufacturer: "Speeder Marine",
    klass: "Boat",
    img: "/img/boat.jpg",
    topSpeed: 125,
    acceleration: 3.9,
    braking: 70,
    handling: 82,
    power: 850,
    weight: "2,100 kg",
    seating: 4,
    drivetrain: "AWD",
    price: 680000,
    priceDisplay: "$680,000",
    purchaseLocation: "DockTease Luxury Marine",
    spawnLocations: ["Leonida Keys Smuggler Marina", "Ocean Beach Marina Slip 14"],
    customizationOptions: ["Twin Supercharged Marine Inboards", "Radar Mast Beacon", "Reinforced Hull Armor", "Submerged Underwater Lighting"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Keys Waterways",
    description: "High-speed offshore interceptor powerboat designed to evade Coastguard cutters across open Atlantic chop and navigate narrow coastal mangrove channels.",
  },
  {
    id: "maverick",
    slug: "buckingham-maverick",
    name: "Buckingham Maverick",
    manufacturer: "Buckingham",
    klass: "Helicopter",
    img: "/img/heli.jpg",
    topSpeed: 160,
    acceleration: 5.2,
    braking: 80,
    handling: 78,
    power: 1100,
    weight: "1,900 kg",
    seating: 4,
    drivetrain: "AWD",
    price: 1550000,
    priceDisplay: "$1,550,000",
    purchaseLocation: "Elitas Travel",
    spawnLocations: ["Vice City International Helipad", "Hospital Helipad Downtown"],
    customizationOptions: ["Search Spotlight", "Emergency Medical Gear", "Tinted VIP Privacy Glass", "High-Altitude Rotor Blades"],
    confidence: "OFFICIAL",
    source: "Rockstar Trailer 1 Aerial Pan",
    description: "The universal twin-engine utility helicopter of Leonida. Reliable passenger transport, rapid heist getaway extraction, and unmatched aerial surveillance.",
  },
  {
    id: "comet-s2",
    slug: "pfister-comet-s2",
    name: "Pfister Comet S2",
    manufacturer: "Pfister",
    klass: "Sports Car",
    img: "/img/car-pink.jpg",
    topSpeed: 198,
    acceleration: 3.2,
    braking: 85,
    handling: 89,
    power: 780,
    weight: "1,410 kg",
    seating: 2,
    drivetrain: "AWD",
    price: 1850000,
    priceDisplay: "$1,850,000",
    purchaseLocation: "Legendary Motorsport",
    spawnLocations: ["Starfish Island Driveways", "Ocean Drive Club Parking"],
    customizationOptions: ["GT Carbon Rear Wing", "Sport Bucket Seats", "Center-Lock Alloy Wheels", "Performance Intercooler"],
    confidence: "CONFIRMED",
    source: "Vice City Beachfront Scene Trailer 1",
    description: "Precision German engineering with rear-engine balance and surgical AWD traction. Carves corners along Biscayne Bay with effortless grace.",
  },
  {
    id: "gauntlet-hellfire",
    slug: "bravado-gauntlet-hellfire",
    name: "Bravado Gauntlet Hellfire",
    manufacturer: "Bravado",
    klass: "Muscle Car",
    img: "/img/car-orange.jpg",
    filter: "hue-rotate(190deg)",
    topSpeed: 182,
    acceleration: 3.6,
    braking: 75,
    handling: 72,
    power: 840,
    weight: "1,880 kg",
    seating: 2,
    drivetrain: "RWD",
    price: 745000,
    priceDisplay: "$745,000",
    purchaseLocation: "Southern San Andreas Super Autos",
    spawnLocations: ["Downtown Drag Strip", "Port Gellhorn Industrial Strip"],
    customizationOptions: ["Widebody Flared Arches", "Supercharger Cowl Induction", "Smoked Headlight Lenses", "Drag Radial Slicks"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Highway Pull Sequence",
    description: "Supercharged Hellcat engine producing tire-shredding torque. Dominates straight-line highway pulls and quarter-mile drag races.",
  },
  {
    id: "cheetah-classic",
    slug: "grotti-cheetah-classic",
    name: "Grotti Cheetah Classic",
    manufacturer: "Grotti",
    klass: "Super Car",
    img: "/img/car-orange.jpg",
    topSpeed: 190,
    acceleration: 3.8,
    braking: 80,
    handling: 83,
    power: 600,
    weight: "1,290 kg",
    seating: 2,
    drivetrain: "RWD",
    price: 1950000,
    priceDisplay: "$1,950,000",
    purchaseLocation: "Legendary Motorsport (Vintage Catalog)",
    spawnLocations: ["The Malibú VIP Lot", "Starfish Island Estate"],
    customizationOptions: ["Pop-Up Headlight Mods", "Testarossa Side Strakes", "Twin Vintage Exhaust", "Period-Correct BBS Wheels"],
    confidence: "REPORTED",
    source: "Rockstar Historical Roster Leaks",
    description: "The definitive 1980s Miami icon. Glistening side strakes, pop-up lights, and intoxicating high-RPM exhaust notes scream retro Vice City royalty.",
  },
  {
    id: "seaplane-dodo",
    slug: "mammoth-dodo-seaplane",
    name: "Mammoth Dodo Seaplane",
    manufacturer: "Mammoth",
    klass: "Plane",
    img: "/img/heli.jpg",
    filter: "hue-rotate(140deg)",
    topSpeed: 135,
    acceleration: 6.0,
    braking: 60,
    handling: 70,
    power: 700,
    weight: "1,600 kg",
    seating: 4,
    drivetrain: "AWD",
    price: 520000,
    priceDisplay: "$520,000",
    purchaseLocation: "Elitas Travel (Maritime Division)",
    spawnLocations: ["Leonida Keys Seaplane Ramp", "Grassrivers Airfield"],
    customizationOptions: ["High-Capacity Fuel Tanks", "Cargo Storage Modification", "Weather Radar", "Dual-Pontoon Mooring Gear"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Coastal Waters",
    description: "Versatile twin-float amphibious plane capable of touching down on calm lagoon waters, coastal bays, or remote rural dirt strips.",
  },
];

/* ------------------------------------------------------------------ */
/* CANONICAL WEAPONS (10 Verified & Tagged Entries)                   */
/* ------------------------------------------------------------------ */
export const canonicalWeapons: CanonicalWeapon[] = [
  {
    id: "m4-carbine",
    slug: "m4-carbine",
    name: "M4 Carbine / Service Rifle",
    klass: "Assault Rifle",
    damage: 68,
    fireRate: 82,
    accuracy: 76,
    range: 72,
    handling: 70,
    reloadTime: "2.35s",
    magazineSize: 30,
    ammoType: "5.56x45mm NATO",
    price: 15500,
    priceDisplay: "$15,500",
    rarity: "Featured",
    locations: ["Downtown Ammu-Nation", "Vice City Police Department Evidence Room", "Military Convoy Drops"],
    attachments: ["Holographic Red Dot Sight", "Tactical Suppressor", "Extended 45-Round Magazine", "Vertical Foregrip", "IR Flashlight"],
    confidence: "OFFICIAL",
    source: "Rockstar Trailer 1 Convenience Store Holdup",
    description: "The gold standard of combat assault rifles. Impeccably balanced fire rate and accuracy across medium-to-long range urban skirmishes.",
    img: "/img/rifle.svg",
  },
  {
    id: "glock-21",
    slug: "glock-21",
    name: "Combat Pistol (Glock 21)",
    klass: "Pistol",
    damage: 34,
    fireRate: 62,
    accuracy: 74,
    range: 42,
    handling: 85,
    reloadTime: "1.70s",
    magazineSize: 15,
    ammoType: ".45 ACP",
    price: 4800,
    priceDisplay: "$4,800",
    rarity: "Common",
    locations: ["All Ammu-Nation Outlets", "Starting weapon with Jason", "Fallen Police Officers"],
    attachments: ["Suppressor Barrel", "Underbarrel Laser Sight", "Extended 22-Round Magazine", "Match Trigger"],
    confidence: "OFFICIAL",
    source: "Jason Holster Promo Key Art",
    description: "Dependable polymer semi-automatic sidearm packing heavy .45 ACP stopping power with quick-draw ergonomics for close-quarters self defense.",
    img: "/img/gunstore.svg",
  },
  {
    id: "tactical-smg",
    slug: "tactical-smg-vom-feuer",
    name: "VOM Feuer Tactical SMG",
    klass: "SMG",
    damage: 32,
    fireRate: 90,
    accuracy: 64,
    range: 48,
    handling: 82,
    reloadTime: "1.90s",
    magazineSize: 32,
    ammoType: "9x19mm Parabellum",
    price: 12500,
    priceDisplay: "$12,500",
    rarity: "Rare",
    locations: ["Port Gellhorn Container Caches", "Downtown Black Market Dealer"],
    attachments: ["Folding Wire Stock", "Tritium Night Sights", "Monolithic Silencer", "Drum 50-Round Mag"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Nightclub Alleyway Shootout",
    description: "High cycle rate submachine gun built for room-clearing and drive-by engagements from moving vehicles. Unmatched close-range DPS.",
    img: "/img/smg-gun.jpg",
  },
  {
    id: "carbine-rifle-mk2",
    slug: "carbine-rifle-mk2",
    name: "Carbine Rifle Mk II",
    klass: "Assault Rifle",
    damage: 78,
    fireRate: 80,
    accuracy: 84,
    range: 82,
    handling: 74,
    reloadTime: "2.10s",
    magazineSize: 40,
    ammoType: "Armor Piercing 5.56mm",
    price: 45000,
    priceDisplay: "$45,000",
    rarity: "Legendary",
    locations: ["Weapon Workshop Safehouses", "Starfish Island Armory Safe"],
    attachments: ["Heavy Barrel", "Thermal Scope", "AP Rounds Magazine", "Muzzle Brake"],
    confidence: "CONFIRMED",
    source: "Verified Leak Asset Metadata",
    description: "Military-grade conversion of the standard service rifle with armor-piercing ballistic rounds and precision thermal optics.",
    img: "/img/rifle.svg",
  },
  {
    id: "heavy-sniper",
    slug: "heavy-sniper-50cal",
    name: "Heavy Sniper .50 BMG",
    klass: "Sniper Rifle",
    damage: 98,
    fireRate: 15,
    accuracy: 96,
    range: 98,
    handling: 35,
    reloadTime: "3.40s",
    magazineSize: 6,
    ammoType: ".50 BMG Anti-Materiel",
    price: 65000,
    priceDisplay: "$65,000",
    rarity: "Epic",
    locations: ["Northern Wilds Lookout Tower", "Port Gellhorn Crane Vantage"],
    attachments: ["Variable Zoom 16x Scope", "Suppressor System", "Explosive Tip Rounds", "Carbon Bipod"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Swampland Rooftop Scene",
    description: "Devastating anti-materiel rifle capable of piercing light vehicle engine blocks, disabling helicopter tail rotors, and delivering instant one-shot neutralizations.",
    img: "/img/rifle.svg",
  },
  {
    id: "pump-shotgun",
    slug: "remington-pump-shotgun",
    name: "Remington Pump Shotgun",
    klass: "Shotgun",
    damage: 86,
    fireRate: 35,
    accuracy: 40,
    range: 28,
    handling: 65,
    reloadTime: "3.80s (Tube Feed)",
    magazineSize: 8,
    ammoType: "12 Gauge 00 Buckshot",
    price: 5200,
    priceDisplay: "$5,200",
    rarity: "Common",
    locations: ["Police Cruisers Trunk", "Rural Grassrivers Gunshops"],
    attachments: ["Flashlight Pump Grip", "Choke Tube", "Slug Round Conversion"],
    confidence: "OFFICIAL",
    source: "Trailer 1 Police Officer Holdup",
    description: "Classic 12-gauge pump-action shotgun offering bone-crushing close-quarters stopping power and wall-breaching capability.",
    img: "/img/gunstore.svg",
  },
  {
    id: "rpg-7",
    slug: "rpg-7-launcher",
    name: "RPG-7 Rocket Launcher",
    klass: "Heavy",
    damage: 100,
    fireRate: 10,
    accuracy: 45,
    range: 85,
    handling: 25,
    reloadTime: "4.50s",
    magazineSize: 1,
    ammoType: "High Explosive Anti-Tank Rocket",
    price: 85000,
    priceDisplay: "$85,000",
    rarity: "Epic",
    locations: ["Cartel Military Caches", "Leonida Keys Sunken Submarine"],
    attachments: ["PGO-7 Optical Scope"],
    confidence: "REPORTED",
    source: "Heist Leak Footage & Code References",
    description: "Shoulder-fired unguided rocket launcher engineered to destroy armored security convoys, patrol boats, and fortification gates.",
    img: "/img/rifle.svg",
  },
  {
    id: "combat-knife",
    slug: "hunting-combat-knife",
    name: "Tactical Bowie Hunting Knife",
    klass: "Melee",
    damage: 48,
    fireRate: 75,
    accuracy: 90,
    range: 5,
    handling: 95,
    reloadTime: "Instant",
    magazineSize: 1,
    ammoType: "Steel Blade",
    price: 350,
    priceDisplay: "$350",
    rarity: "Common",
    locations: ["Outdoor Gear Stores", "Swamp Hunters Cabins"],
    attachments: ["Serrated Spine Edge", "Carbon Fiber Grip"],
    confidence: "OFFICIAL",
    source: "Trailer 1 Swamp Wildlife Sequence",
    description: "Razor-sharp full-tang carbon steel hunting knife used for silent takedowns, skinning swamp wildlife, and close combat survival.",
    img: "/img/gunstore.svg",
  },
  {
    id: "ak-74",
    slug: "ak-74-kalashnikov",
    name: "Kalashnikov AK-74",
    klass: "Assault Rifle",
    damage: 72,
    fireRate: 70,
    accuracy: 68,
    range: 70,
    handling: 66,
    reloadTime: "2.60s",
    magazineSize: 30,
    ammoType: "5.45x39mm Soviet",
    price: 11800,
    priceDisplay: "$11,800",
    rarity: "Rare",
    locations: ["Smuggler Docks in Leonida Keys", "Underground Chop Shops"],
    attachments: ["Bakelite Extended 40-Round Mag", "Russian Kobra Red Dot", "Muzzle Compensator"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Cartel Port Scene",
    description: "Rugged and virtually unjammable assault rifle. Hits harder per round than western counterparts, ideal for gritty gangland confrontations.",
    img: "/img/rifle.svg",
  },
  {
    id: "pipe-bomb",
    slug: "improvised-pipe-bomb",
    name: "Improvised Pipe Bomb",
    klass: "Throwable",
    damage: 92,
    fireRate: 20,
    accuracy: 60,
    range: 30,
    handling: 75,
    reloadTime: "N/A",
    magazineSize: 5,
    ammoType: "Nails & Black Powder",
    price: 750,
    priceDisplay: "$750",
    rarity: "Common",
    locations: ["Crafting Bench Safehouse", "Smuggler Stashes"],
    attachments: ["Remote Electronic Detonator"],
    confidence: "REPORTED",
    source: "Story Leak Mission Notes",
    description: "Handmade fragmentation explosive wrapped in steel piping. Devastating blast radius against police barricades and bank teller security glass.",
    img: "/img/gunstore.svg",
  },
];

/* ------------------------------------------------------------------ */
/* CANONICAL MISSIONS (8 Verified & Tagged Entries)                   */
/* ------------------------------------------------------------------ */
export const canonicalMissions: CanonicalMission[] = [
  {
    id: "m-1",
    slug: "welcome-to-leonida",
    title: "Welcome to Leonida",
    type: "Main Story",
    character: "Lucia",
    difficulty: "Easy",
    duration: "15 min",
    district: "Vice City Downtown",
    cashReward: 1500,
    cashRewardDisplay: "$1,500",
    otherRewards: ["First Safehouse Key", "Lucia's Track Jacket", "Burner Phone"],
    requirements: ["Game Opening Prologue"],
    objectives: [
      "Exit the Leonida State Correctional facility",
      "Meet probation officer at Vice City Civic Center",
      "Rendezvous with Jason at the Ocean Drive Motel",
      "Evade the undercover patrol unit without firing shots",
    ],
    choices: [
      "Take the coastal highway route (faster, higher police visibility)",
      "Cut through the railyard alleyways (slower, zero heat)",
    ],
    outcomes: ["Establishes baseline trust between Lucia & Jason", "Unlocks free roaming across eastern Vice City"],
    unlocks: ["Ocean Drive Motel Safehouse", "Bravado Banshee spawn"],
    relatedMissions: ["back-in-vice"],
    confidence: "OFFICIAL",
    source: "Rockstar Trailer 1 Opening & Dialogue",
    description: "Lucia's return to the neon-drenched streets of Vice City after incarceration, reuniting with Jason to plot their future in an unforgiving state.",
    guideTips: ["Keep your vehicle speed below 50 mph through the police patrol checkpoint to prevent immediate 2-star wanted level."],
    img: "/img/char-lucia.jpg",
  },
  {
    id: "m-2",
    slug: "back-in-vice",
    title: "Back in Vice: The Store Heist",
    type: "Main Story",
    character: "Both",
    difficulty: "Medium",
    duration: "20 min",
    district: "Ocean Drive Waterfront",
    cashReward: 18500,
    cashRewardDisplay: "$18,500",
    otherRewards: ["Duffel Bag Gear", "Unlocks Ammu-Nation Discount"],
    requirements: ["Complete 'Welcome to Leonida'"],
    objectives: [
      "Drive to the liquor store on 8th Street",
      "Lucia covers the cashier while Jason breaches the back office safe",
      "Drill the mechanical safe lock within 90 seconds",
      "Escape local police cruiser pursuit using the beach underpass",
    ],
    choices: [
      "Quiet drill method: Takes longer, prevents alarm trigger",
      "C4 explosive breach: Instant cash, immediately triggers 3-star wanted level",
    ],
    outcomes: ["Player can switch freely between Lucia and Jason during gameplay"],
    unlocks: ["Switch Character mechanic", "Convenience store robbing dynamic encounters"],
    relatedMissions: ["welcome-to-leonida", "the-score-bank-of-keys"],
    confidence: "OFFICIAL",
    source: "Rockstar Trailer 1 Bandana Sequence",
    description: "The signature Bonnie & Clyde robbery showcased in Trailer 1. Coordinate dual protagonist actions under high pressure.",
    guideTips: ["Switch to Jason while Lucia manages the crowd so you can keep the cashier intimidated while cracking the lock."],
    img: "/img/hero-dark.jpg",
  },
  {
    id: "m-3",
    slug: "the-score-bank-of-keys",
    title: "The Score: Bank of the Keys",
    type: "Heist",
    character: "Both",
    difficulty: "Hard",
    duration: "35 min",
    district: "Leonida Keys",
    cashReward: 250000,
    cashRewardDisplay: "$250,000",
    otherRewards: ["Speeder Vortex Boat", "Offshore Bank Account Access"],
    requirements: ["Complete Heist Prep: Marine Smuggler & Heavy Weapon drop"],
    objectives: [
      "Infiltrate Keys regional depository branch via rear water dock",
      "Disable security camera circuit breaker with electromagnetic jammer",
      "Blow the vault gate with thermite gel",
      "Loot safe deposit safety lockers #101 through #114",
      "Fight through SWAT barricade to the getaway speedboat",
      "Lose Coastguard patrol helicopters in the mangrove labyrinth",
    ],
    choices: [
      "Loud Approach: Heavy body armor + RPG suppressing fire",
      "Stealth Scuba Approach: Night infiltration via sewer intake tube",
    ],
    outcomes: ["Unlocks major heist planning board in player safehouse", "Triggers bounty alert across Keys district"],
    unlocks: ["Heist Planner Tool", "Keys Smuggler Marina"],
    relatedMissions: ["back-in-vice", "the-exchange-port-ambush"],
    confidence: "CONFIRMED",
    source: "Rockstar Verified Leak Documentation & Assets",
    description: "Major chapter climax heist targeting the coastal regional bank in the Keys. High-stakes boat chase through shallow mangroves.",
    guideTips: ["Use the Speeder Vortex's tight turning radius inside the narrow mangrove channels to make the chasing Coastguard boats run aground."],
    img: "/img/boat.jpg",
  },
  {
    id: "m-4",
    slug: "the-exchange-port-ambush",
    title: "The Exchange: Port Gellhorn Ambush",
    type: "Main Story",
    character: "Jason",
    difficulty: "Hard",
    duration: "25 min",
    district: "Port Gellhorn Industrial Docks",
    cashReward: 42000,
    cashRewardDisplay: "$42,000",
    otherRewards: ["Tactical SMG Drop", "Port Gellhorn Safehouse Access"],
    requirements: ["Complete 'The Score: Bank of the Keys'"],
    objectives: [
      "Meet cartel representative inside Container Yard 4",
      "Inspect the shipment of military hardware",
      "Survive rival syndicate ambush from shipping crane snipers",
      "Provide sniper covering fire for Lucia as she secures the semi-truck",
      "Drive the cargo truck back to Little Haiti chop shop",
    ],
    choices: [
      "Climb crane for high ground sniper advantage",
      "Stay grounded behind concrete forklift barriers with shotgun",
    ],
    outcomes: ["Port Gellhorn district unlocked for property investment"],
    unlocks: ["Heavy Sniper .50 BMG", "Port Gellhorn Container Safehouse"],
    relatedMissions: ["the-score-bank-of-keys"],
    confidence: "CONFIRMED",
    source: "Verified Leak Footage Analysis",
    description: "High-octane industrial firefight amidst towering cargo container stacks, concluding with a heavy truck escape.",
    guideTips: ["Shoot the explosive fuel tanks mounted on enemy pickup trucks to eliminate multiple cartel gunners in a single blast."],
    img: "/img/smg-gun.jpg",
  },
  {
    id: "m-5",
    slug: "grassrivers-gator-bounty",
    title: "Bounty: The Gator Poacher",
    type: "Side Contract",
    character: "Any",
    difficulty: "Medium",
    duration: "18 min",
    district: "Grassrivers Swamps",
    cashReward: 12500,
    cashRewardDisplay: "$12,500",
    otherRewards: ["Rare Alligator Leather Jacket", "Hunting Rifle Blueprint"],
    requirements: ["Unlock Grassrivers territory"],
    objectives: [
      "Talk to Wildlife Officer at Grassrivers Ranger Station",
      "Follow swamp tire tracks using thermal vision on the airboat",
      "Confront the illegal poaching camp in the deep bayou",
      "Subdue poacher boss without killing the endangered albino alligator",
    ],
    choices: [
      "Take poacher in alive (bonus $5,000 law enforcement reward)",
      "Accept poacher's bribe ($15,000 cash, fail ranger reputation)",
    ],
    outcomes: ["Ranger Station becomes friendly vendor for wilderness gear"],
    unlocks: ["Everglades Fanboat", "Wildlife Photography Challenge"],
    relatedMissions: [],
    confidence: "CONFIRMED",
    source: "Trailer 1 Gator Extraction Sequence",
    description: "Wild Florida-style eccentric side contract hunting down rogue swamp poachers operating inside restricted national park swamplands.",
    guideTips: ["Watch the water surface for gator ripples — falling off your airboat in the deep bayou results in instant wildlife attack."],
    img: "/img/car-pickup.jpg",
  },
  {
    id: "m-6",
    slug: "south-beach-drag-circuit",
    title: "South Beach Midnight Drag Championship",
    type: "Side Contract",
    character: "Any",
    difficulty: "Medium",
    duration: "12 min",
    district: "Ocean Drive Waterfront",
    cashReward: 25000,
    cashRewardDisplay: "$25,000",
    otherRewards: ["Turbo Tuning Stage 3 Upgrade", "Custom Neon Underglow Kit"],
    requirements: ["Own a tuned Sports or Muscle class vehicle"],
    objectives: [
      "Arrive at Ocean Drive underground meet by 23:00",
      "Defeat rival contender in 3-round drag elimination race",
      "Perfect-launch off the green light without spinning tires",
      "Escape the police sweep that raids the finish line",
    ],
    choices: [
      "Use Nitrous on the 2nd gear shift for maximum torque",
      "Save Nitrous for top-end speed in final quarter mile",
    ],
    outcomes: ["Unlocks midnight street racing tournament across Leonida"],
    unlocks: ["Street Racing Club rep", "Los Santos Customs High-End Parts"],
    relatedMissions: [],
    confidence: "REPORTED",
    source: "Street Racing Leak Audio Assets",
    description: "Electrifying midnight illegal drag competition against Vice City's top street tuners under flashing neon palm trees.",
    guideTips: ["Warm up your tires during staging by holding brake + gas until tire smoke turns dense white for 100% launch grip."],
    img: "/img/car-orange.jpg",
  },
  {
    id: "m-7",
    slug: "starfish-island-mansion-heist",
    title: "Starfish Island Tech Mogul Infiltration",
    type: "Heist",
    character: "Both",
    difficulty: "Extreme",
    duration: "40 min",
    district: "Starfish Island",
    cashReward: 480000,
    cashRewardDisplay: "$480,000",
    otherRewards: ["Grotti Visione Supercar", "Encrypted Crypto Ledger"],
    requirements: ["Level 25 Criminal Rep", "Hacking Tool Kit"],
    objectives: [
      "Swim with rebreathers across Biscayne bay to the private mansion dock",
      "Hack digital security cameras at the swimming pool patio",
      "Extract biometric thumbprint from sleeping executive",
      "Open subterranean crypto server room vault",
      "Steal the prototype Grotti Visione stored in the private subterranean showroom",
      "Ram the mansion front gates and survive multi-patrol pursuit across bridge",
    ],
    choices: [
      "Silent EMP blackout: Disables alarms and lights for 3 minutes",
      "Disguised catering staff infiltration: Walk in through service entrance",
    ],
    outcomes: ["Unlocks highest tier luxury property purchases", "Media news report on radio stations"],
    unlocks: ["Starfish Island Penthouse purchase", "Grotti Visione"],
    relatedMissions: ["the-score-bank-of-keys"],
    confidence: "REPORTED",
    source: "High-End Mansion Asset Leaks",
    description: "Glamorous, high-difficulty modern heist infiltrating a tech billionaire's fortress estate on Starfish Island.",
    guideTips: ["Disable the backup generator behind the tennis court first so emergency floodlights do not illuminate your escape."],
    img: "/img/car-purple.jpg",
  },
  {
    id: "m-8",
    slug: "malibu-vip-protection",
    title: "The Malibú Club: Syndicate Escort",
    type: "Side Contract",
    character: "Jason",
    difficulty: "Hard",
    duration: "22 min",
    district: "Ocean Drive Waterfront",
    cashReward: 35000,
    cashRewardDisplay: "$35,000",
    otherRewards: ["VIP Club Access", "Armored Bravado Sedan"],
    requirements: ["Complete 'Back in Vice'"],
    objectives: [
      "Meet nightclub owner in the upstairs VIP mezzanine",
      "Identify undercover hitmen scanning the dancefloor",
      "Extract the VIP contact through the rear kitchen alleyway",
      "Repel motorbike attackers during high-speed highway convoy protection",
    ],
    choices: [
      "Engage hitmen inside club: High civilian panic, fast outcome",
      "Lure hitmen to back parking lot: Controlled clean firefight",
    ],
    outcomes: ["Nightclub owner offers weekly passive cut of club profits"],
    unlocks: ["The Malibú Club purchase option", "Nightclub safe passive collection"],
    relatedMissions: [],
    confidence: "CONFIRMED",
    source: "Nightlife Audio Leak & Trailer 1 Party Scenes",
    description: "Classic neon Vice City nightclub protection mission with authentic 80s synth vibes and explosive urban highway defense.",
    guideTips: ["Use the armored sedan's bullet-resistant rear glass to protect the VIP from trailing submachine gun fire."],
    img: "/img/vice-sunset.svg",
  },
];

/* ------------------------------------------------------------------ */
/* CANONICAL LOCATIONS & MAP POIS (14 Verified Points of Interest)     */
/* ------------------------------------------------------------------ */
export const canonicalLocations: CanonicalLocation[] = [
  {
    id: "loc-ocean-drive",
    slug: "ocean-drive-waterfront",
    name: "Ocean Drive & South Beach Waterfront",
    district: "Ocean Drive",
    category: "Point of Interest",
    desc: "The world-famous neon art-deco strip. Lined with pastel hotels, bustling outdoor cafes, supercar valets, and sun-soaked coastal beaches.",
    top: "56%",
    left: "64%",
    hours: "Open 24/7 (Nightlife peaks 22:00 - 05:00)",
    threatLevel: "Medium",
    relatedVehicles: ["bravado-banshee-gts", "pfister-comet-s2"],
    relatedMissions: ["back-in-vice", "south-beach-drag-circuit"],
    confidence: "OFFICIAL",
    source: "Rockstar Trailer 1 Main Showcase",
    img: "/img/hero-dark.jpg",
    verified: true,
  },
  {
    id: "loc-downtown-ammu",
    slug: "ammu-nation-downtown",
    name: "Ammu-Nation Flagship — Downtown",
    district: "Vice City Downtown",
    category: "Shop",
    desc: "Premier military-grade firearms retailer with indoor underground shooting range, heavy armor racks, and high-caliber ammo restocking.",
    top: "46%",
    left: "58%",
    hours: "08:00 – 23:00",
    threatLevel: "Low",
    relatedWeapons: ["m4-carbine", "glock-21", "carbine-rifle-mk2"],
    confidence: "OFFICIAL",
    source: "Trailer 1 Ammu-Nation Exterior Banner",
    img: "/img/gunstore.svg",
    verified: true,
  },
  {
    id: "loc-malibu-club",
    slug: "the-malibu-nightclub",
    name: "The Malibú Neon Nightclub",
    district: "Ocean Drive Waterfront",
    category: "Business",
    desc: "Legendary multi-level 80s-inspired oceanfront nightclub. High-profile syndicate contacts, VIP bottle service, and massive weekly passive revenue.",
    top: "58%",
    left: "62%",
    hours: "21:00 – 06:00",
    threatLevel: "Medium",
    relatedMissions: ["malibu-vip-protection"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Club Interior Shots",
    img: "/img/vice-sunset.svg",
    verified: true,
  },
  {
    id: "loc-port-gellhorn",
    slug: "port-gellhorn-docks",
    name: "Port Gellhorn Cargo Depots & Railyards",
    district: "Port Gellhorn",
    category: "Point of Interest",
    desc: "Sprawling industrial shipping hub on the western coast. Massive container yards, freight cranes, underground chop shops, and contraband shipping routes.",
    top: "42%",
    left: "35%",
    hours: "Open 24/7 (Heavy freight traffic)",
    threatLevel: "High",
    relatedVehicles: ["western-reever"],
    relatedWeapons: ["tactical-smg-vom-feuer", "ak-74-kalashnikov"],
    relatedMissions: ["the-exchange-port-ambush"],
    confidence: "OFFICIAL",
    source: "Trailer 1 Port Gellhorn Road Signs",
    img: "/img/smg-gun.jpg",
    verified: true,
  },
  {
    id: "loc-keys-marina",
    slug: "leonida-keys-smuggler-marina",
    name: "Leonida Keys Smuggler Marina",
    district: "Leonida Keys",
    category: "Garage",
    desc: "Archipelago boat slips, fueling docks, and speed boat tuning workshops catering to deep-sea anglers and coastal contraband runners.",
    top: "72%",
    left: "45%",
    hours: "Open 24/7",
    threatLevel: "Medium",
    relatedVehicles: ["speeder-vortex"],
    relatedMissions: ["the-score-bank-of-keys"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Keys Bridge & Waterways",
    img: "/img/boat.jpg",
    verified: true,
  },
  {
    id: "loc-grassrivers-marsh",
    slug: "grassrivers-everglades-sanctuary",
    name: "Grassrivers Swamplands & Airboat Outpost",
    district: "Grassrivers",
    category: "Point of Interest",
    desc: "Endless wilderness wetlands inhabited by dangerous wildlife, airboat rental shacks, abandoned cold-war radio beacons, and hidden bootlegger stills.",
    top: "35%",
    left: "55%",
    hours: "Open 24/7 (High danger after dark)",
    threatLevel: "High",
    relatedVehicles: ["maibatsu-sanchez", "western-reever"],
    relatedWeapons: ["hunting-combat-knife", "remington-pump-shotgun"],
    relatedMissions: ["grassrivers-gator-bounty"],
    confidence: "OFFICIAL",
    source: "Rockstar Trailer 1 Swampland Airboat Pan",
    img: "/img/car-pickup.jpg",
    verified: true,
  },
  {
    id: "loc-starfish-mansion",
    slug: "starfish-island-estates",
    name: "Starfish Island Luxury Enclave",
    district: "Starfish Island",
    category: "Property",
    desc: "Ultra-exclusive gated island community featuring billionaire waterfront mansions, private boat docks, and exotic hypercar collections.",
    top: "52%",
    left: "59%",
    hours: "Gated Access (Armed Security)",
    threatLevel: "Restricted Area",
    relatedVehicles: ["grotti-visione", "pfister-comet-s2"],
    relatedMissions: ["starfish-island-mansion-heist"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Luxury Villa Helicopter Sequence",
    img: "/img/car-purple.jpg",
    verified: true,
  },
  {
    id: "loc-via-airport",
    slug: "vice-city-international-airport",
    name: "Vice City International Airport (VIA)",
    district: "Airport / Western Vice",
    category: "Airport / Helipad",
    desc: "Massive civil aviation hub featuring commercial runways, private jet hangars, police helipads, and extreme stunt ramp launch points.",
    top: "48%",
    left: "48%",
    hours: "Open 24/7",
    threatLevel: "Restricted Area",
    relatedVehicles: ["buckingham-maverick", "mammoth-dodo-seaplane"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Plane Takeoff Background",
    img: "/img/heli.jpg",
    verified: true,
  },
  {
    id: "loc-ufo-mural",
    slug: "cryptic-ufo-radar-dome",
    name: "Cryptic UFO Swamplands Mural",
    district: "Grassrivers",
    category: "Easter Egg",
    desc: "Mysterious extraterrestrial artwork painted on an abandoned Cold War military radar installation. Emits strange audio frequencies during thunderstorms.",
    top: "32%",
    left: "54%",
    hours: "00:00 – 04:00 (Rain/Thunderstorm only)",
    threatLevel: "Low",
    confidence: "CONFIRMED",
    source: "In-Game Leak Mystery Documentation",
    img: "/img/ufo-mural.jpg",
    verified: true,
  },
  {
    id: "loc-underground-garage",
    slug: "customs-garage-ocean-drive",
    name: "Vice City Customs — Ocean Drive",
    district: "Ocean Drive",
    category: "Garage",
    desc: "High-end vehicle modification garage offering widebody kits, engine dyno tuning, custom neon wraps, and instant resprays.",
    top: "57%",
    left: "63%",
    hours: "Open 24/7",
    threatLevel: "Low",
    relatedVehicles: ["bravado-banshee-gts", "declasse-tulip"],
    confidence: "OFFICIAL",
    source: "Trailer 1 Lowrider & Tuner Car Meet",
    img: "/img/garage.jpg",
    verified: true,
  },
  {
    id: "loc-bayfront-penthouse",
    slug: "high-end-bayfront-penthouse",
    name: "High-End Biscayne Bayfront Penthouse",
    district: "Vice City Downtown",
    category: "Property",
    desc: "Luxury glass penthouse overlooking the Biscayne bay and neon skyline with private 10-car garage, helipad roof access, and security armory.",
    top: "50%",
    left: "60%",
    hours: "Private Residence",
    threatLevel: "Low",
    confidence: "CONFIRMED",
    source: "Vice City High-Rise Leaks",
    img: "/img/apartment.jpg",
    verified: true,
  },
  {
    id: "loc-northern-lookout",
    slug: "northern-wilds-fire-lookout",
    name: "Northern Wilds Fire Lookout Peak",
    district: "Northern Wilds",
    category: "Point of Interest",
    desc: "Elevated scenic vantage tower atop the state's highest ridge offering 360-degree views across forests, logging trails, and distant city lights.",
    top: "22%",
    left: "34%",
    hours: "Open 24/7",
    threatLevel: "Low",
    relatedWeapons: ["heavy-sniper-50cal"],
    confidence: "CONFIRMED",
    source: "Wilderness Leaks & Map Topography",
    img: "/img/hero-dark.jpg",
    verified: true,
  },
  {
    id: "loc-port-safehouse",
    slug: "port-gellhorn-underground-safehouse",
    name: "Port Gellhorn Underground Safehouse",
    district: "Port Gellhorn",
    category: "Safehouse",
    desc: "Reinforced industrial basement safehouse equipped with escape water tunnel to cargo docks, weapon modification bench, and vehicle stash.",
    top: "44%",
    left: "33%",
    hours: "Story Unlocked",
    threatLevel: "Medium",
    relatedMissions: ["the-exchange-port-ambush"],
    confidence: "CONFIRMED",
    source: "Story Mission Leak Documents",
    img: "/img/garage.jpg",
    verified: true,
  },
  {
    id: "loc-submerged-cache",
    slug: "submerged-biscayne-smuggler-cache",
    name: "Submerged Reef Smuggler Cache",
    district: "Biscayne Bay Reef",
    category: "Collectible",
    desc: "Waterproof steel cargo chest dropped onto coastal coral reef shelf during high-speed Coastguard chase. Requires scuba apparatus.",
    top: "62%",
    left: "67%",
    hours: "Requires Scuba Gear",
    threatLevel: "Medium",
    confidence: "CONFIRMED",
    source: "Underwater Marine Assets",
    img: "/img/cache-chest.jpg",
    verified: true,
  },
];

/* ------------------------------------------------------------------ */
/* CANONICAL PROPERTIES (6 Verified & Tagged Entries)                 */
/* ------------------------------------------------------------------ */
export const canonicalProperties: CanonicalProperty[] = [
  {
    id: "prop-biscayne-penthouse",
    slug: "biscayne-bayfront-penthouse",
    name: "Biscayne Sky Penthouse",
    district: "Vice City Downtown",
    type: "Luxury Penthouse",
    price: 3500000,
    priceDisplay: "$3,500,000",
    garageCapacity: 10,
    passiveIncomePerHour: 0,
    passiveIncomeDisplay: "None (Private Luxury)",
    features: ["Private Rooftop Helipad", "10-Car Underground Showcase Garage", "Panoramic 360° Bay Glass", "Security Armory Room"],
    upgrades: ["Custom Interior Themes", "Bulletproof Window Glass", "Gun Locker & Armor Station", "Private Bartender"],
    requirements: ["Account balance >= $3.5M", "Complete Chapter 2 Story"],
    confidence: "CONFIRMED",
    source: "Downtown Luxury Real Estate Leaks",
    desc: "The ultimate status symbol in Leonida. Overlook the glittering ocean and Vice City neon lights from your private high-rise sanctuary.",
    img: "/img/apartment.jpg",
    mapCoords: { top: "50%", left: "60%" },
  },
  {
    id: "prop-malibu-club",
    slug: "the-malibu-nightclub-property",
    name: "The Malibú Nightclub & Syndicate Lounge",
    district: "Ocean Drive Waterfront",
    type: "Nightclub",
    price: 2200000,
    priceDisplay: "$2,200,000",
    garageCapacity: 4,
    passiveIncomePerHour: 18500,
    passiveIncomeDisplay: "$18,500 / hr ($444,000 / day max popularity)",
    features: ["Daily Cash Vault Collection", "Underground Nightclub Syndicate Office", "4-Car VIP Valet Garage", "Private VIP Booths"],
    upgrades: ["Top-Tier Resident DJ", "Heavy Security Bouncers", "VIP Champagne Bar", "Dry Ice & Laser System"],
    requirements: ["Complete 'The Malibú: Syndicate Escort' Mission"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Nightlife Sequences & Code Strings",
    desc: "Turn your street hustle into a legitimate entertainment empire. High cash flow with minimal police suspicion when popularity is managed.",
    img: "/img/vice-sunset.svg",
    mapCoords: { top: "58%", left: "62%" },
  },
  {
    id: "prop-little-haiti-chopshop",
    slug: "little-haiti-chop-shop",
    name: "Little Haiti Underground Chop Shop",
    district: "Little Haiti",
    type: "Chop Shop Garage",
    price: 850000,
    priceDisplay: "$850,000",
    garageCapacity: 8,
    passiveIncomePerHour: 12000,
    passiveIncomeDisplay: "$12,000 / hr + $45,000 per exotic vehicle dismantled",
    features: ["Hydraulic Vehicle Lifts", "Automated Parts Stripper", "Forged Title VIN Laser Printer", "8-Vehicle Stash Bay"],
    upgrades: ["Heavy Lift Crane", "Faster Disassembly Crew", "Police Heat Scrambler", "Custom Respray Booth"],
    requirements: ["Complete 'Little Haiti Turf Disruption'"],
    confidence: "CONFIRMED",
    source: "Trailer 1 Lowrider & Garage Scenes",
    desc: "Discreet industrial garage where stolen supercars and muscle cruisers are scrubbed, stripped into valuable salvage, or fitted with cold plates.",
    img: "/img/garage.jpg",
    mapCoords: { top: "45%", left: "56%" },
  },
  {
    id: "prop-port-gellhorn-warehouse",
    slug: "port-gellhorn-cargo-warehouse",
    name: "Port Gellhorn Cargo Terminal Warehouse",
    district: "Port Gellhorn",
    type: "Commercial Warehouse",
    price: 1450000,
    priceDisplay: "$1,450,000",
    garageCapacity: 6,
    passiveIncomePerHour: 15000,
    passiveIncomeDisplay: "$15,000 / hr + Large Contraband Export Sales",
    features: ["Deep-Water Freight Slip Access", "High-Capacity Forklifts", "Secure Contraband Lockers", "Semi-Truck Loading Bay"],
    upgrades: ["Armored Delivery Flatbeds", "CCTV Perimeter Grid", "Automated Inventory Sorting"],
    requirements: ["Complete Chapter 3 Smuggler storyline"],
    confidence: "CONFIRMED",
    source: "Industrial Docks Leak Assets",
    desc: "Massive commercial storage terminal for consolidating high-value narcotics, counterfeit luxury electronics, and export weapons.",
    img: "/img/smg-gun.jpg",
    mapCoords: { top: "42%", left: "35%" },
  },
  {
    id: "prop-keys-marina-dock",
    slug: "leonida-keys-marina-slips",
    name: "Leonida Keys Private Marina Slips",
    district: "Leonida Keys",
    type: "Marina Dock",
    price: 980000,
    priceDisplay: "$980,000",
    garageCapacity: 2,
    passiveIncomePerHour: 8500,
    passiveIncomeDisplay: "$8,500 / hr ($204,000 / day)",
    features: ["4 Covered Deep-Water Boat Slips", "Fuel Dock Pumps", "Tackle & Bait Shop Front", "Private Seaplane Mooring"],
    upgrades: ["High-Octane Marine Pumps", "Night Navigation Beacons", "Heavy Drydock Winch"],
    requirements: ["Complete 'The Score: Bank of the Keys'"],
    confidence: "REPORTED",
    source: "Maritime Real Estate Leaks",
    desc: "Scenic tropical marina in the Keys functioning as both a tranquil coastal retreat and a strategic maritime launchpad for offshore smuggling.",
    img: "/img/boat.jpg",
    mapCoords: { top: "72%", left: "45%" },
  },
  {
    id: "prop-ocean-beach-motel",
    slug: "ocean-beach-starter-motel",
    name: "Ocean Beach Safehouse Suite",
    district: "Ocean Drive Waterfront",
    type: "Safehouse",
    price: 0,
    priceDisplay: "FREE (Story Unlock)",
    garageCapacity: 2,
    passiveIncomePerHour: 0,
    passiveIncomeDisplay: "None (Starting Safehouse)",
    features: ["Wardrobe & Outfit Changer", "Weapon Storage Trunk", "2-Car Curbside Parking", "Sleep & Save Bed"],
    upgrades: ["Radio Stations Tuner", "Wall Heist Planning Board"],
    requirements: ["Prologue Story Progression"],
    confidence: "OFFICIAL",
    source: "Trailer 1 Motel Room Shot",
    desc: "Your starting base of operations in Vice City. Retro art-deco motel room with direct ocean view where Lucia and Jason strategize.",
    img: "/img/hero-dark.jpg",
    mapCoords: { top: "56%", left: "64%" },
  },
];

/* ------------------------------------------------------------------ */
/* CANONICAL COLLECTIBLES (6 Representative Types)                    */
/* ------------------------------------------------------------------ */
export const canonicalCollectibles: CanonicalCollectible[] = [
  {
    id: "col-pkg-01",
    slug: "hidden-package-ocean-view",
    title: "Hidden Package #01: Ocean View Marina Pier",
    category: "Hidden Packages",
    district: "Ocean Beach",
    reward: "$5,000 Cash + Combat Pistol Ammo Cache",
    requirements: "None (Explore under the wooden boardwalk)",
    description: "Waterproof wrapped contraband package wedged under the wooden pilings of South Beach marina pier.",
    guideTip: "Crouch under the eastern boardwalk at low tide or swim underneath to locate the blinking green LED beacon.",
    coordinates: { top: "58%", left: "65%" },
    confidence: "CONFIRMED",
    source: "Verified Collectibles Manifest",
    img: "/img/crate.svg",
  },
  {
    id: "col-stunt-01",
    slug: "stunt-jump-airport-express",
    title: "Stunt Jump #08: Airport Highway Ramp",
    category: "Stunt Jumps",
    district: "VIA Airport",
    reward: "500 RP + Stunt Driver Achievement Progress",
    requirements: "Fast sports car or motorbike (minimum 120 mph launch)",
    description: "Billboard maintenance steel ramp launching over six lanes of highway traffic leading to the commercial airport terminal.",
    guideTip: "Line up your approach from 300 meters back on the service road. Land cleanly on four wheels without hitting street lamps.",
    coordinates: { top: "49%", left: "50%" },
    confidence: "CONFIRMED",
    source: "Trailer 1 Stunt Geometry",
    img: "/img/car-orange.jpg",
  },
  {
    id: "col-radio-01",
    slug: "rebel-radio-antenna-wave103",
    title: "Rebel Radio Station Transmitter #04",
    category: "Rebel Radio",
    district: "Downtown Vice City",
    reward: "Unlocks Wave 103 Underground Radio Track & $2,500",
    requirements: "Climb maintenance ladder to rooftop transmission tower",
    description: "Pirate radio frequency repeater unit clamped to the cellular antenna array atop the downtown bank building.",
    guideTip: "Take the external fire escape stairs to roof level. Cut the security padlock with bolt cutters to access the relay box.",
    coordinates: { top: "47%", left: "59%" },
    confidence: "CONFIRMED",
    source: "In-Game Audio Asset References",
    img: "/img/hero-dark.jpg",
  },
  {
    id: "col-wildlife-01",
    slug: "wildlife-photo-pink-flamingo",
    title: "Wildlife Photography: Rare Caribbean Flamingo",
    category: "Wildlife Photos",
    district: "Grassrivers Sanctuary",
    reward: "$3,500 Cash + Audubon Nature Perk",
    requirements: "Telephoto Camera Lens (Equip from weapon wheel)",
    description: "Capture a close-up clear photograph of the rare bright-pink Caribbean Flamingo wading through the swamp reeds.",
    guideTip: "Crouch and approach against the wind so birds do not scatter. Capture photo while subject is centered in sunlight.",
    coordinates: { top: "37%", left: "53%" },
    confidence: "OFFICIAL",
    source: "Trailer 1 Wildlife Showcase",
    img: "/img/flamingo.svg",
  },
  {
    id: "col-part-01",
    slug: "weapon-part-titanium-suppressor",
    title: "Unique Weapon Part: Titanium Pistol Suppressor",
    category: "Weapon Parts",
    district: "Port Gellhorn Docks",
    reward: "Unlocks Free Suppressor Mount for all Handguns",
    requirements: "Search inside open blue cargo container #714",
    description: "Precision-milled aerospace-grade titanium suppressor prototype left behind in an abandoned smuggler crate.",
    guideTip: "Container is guarded by two cartel sentries. Eliminate them silently or enter via roof hatch at night.",
    coordinates: { top: "41%", left: "34%" },
    confidence: "CONFIRMED",
    source: "Weapon Crafting Leak Data",
    img: "/img/gunstore.svg",
  },
  {
    id: "col-easter-01",
    slug: "easter-egg-ufo-dome-graffiti",
    title: "Easter Egg: Mysterious Swampland Alien Mural",
    category: "Easter Eggs",
    district: "Grassrivers Marshlands",
    reward: "Cryptic Radio Signal + Alien Investigator Badge",
    requirements: "Visit between 00:00 and 04:00 during heavy rain",
    description: "Luminescent graffiti depicting a flying saucer hovering over the Everglades. Emits harmonic frequency on CB channel 9.",
    guideTip: "Set your in-game time or wait for an evening storm. The mural glows with green bioluminescent paint in pitch darkness.",
    coordinates: { top: "32%", left: "54%" },
    confidence: "CONFIRMED",
    source: "Trailer 1 Mystery Teasers",
    img: "/img/ufo-mural.jpg",
  },
];

/* ------------------------------------------------------------------ */
/* CANONICAL MONEY-MAKING METHODS (5 Verified & Tagged Strategies)     */
/* ------------------------------------------------------------------ */
export const canonicalMoneyMethods: CanonicalMoneyMethod[] = [
  {
    id: "method-heists",
    title: "Keys Depository & High-Stakes Heists",
    category: "Heist",
    moneyPerHour: 280000,
    moneyPerHourDisplay: "$250,000 – $320,000 / hour",
    difficulty: "Hard",
    minInvestment: 50000,
    minInvestmentDisplay: "$50,000 (Prep equipment)",
    timeToPayout: "35–45 minutes per run",
    soloFriendly: true,
    coopRecommended: true,
    riskTolerance: "High",
    requiredLevel: "Intermediate",
    requirements: ["Complete Chapter 2 Story", "Unlock Heist Prep Board", "Fast Getaway Vehicle"],
    strategySteps: [
      "Select the Stealth Scuba entry route to bypass ground alarm sensors.",
      "Bring thermite charges instead of loud drills for 60% faster vault entry.",
      "Equip heavy body armor and tactical SMG for the final dockside extraction.",
      "Evade 4-star wanted level by cutting engines inside mangrove channels.",
    ],
    whyRecommended: "Highest liquid cash return per hour in the game. Best method for rapidly financing supercars and luxury penthouses.",
    confidence: "CONFIRMED",
    source: "Rockstar Heist Mechanics Leaks",
  },
  {
    id: "method-nightclub",
    title: "Nightclub & VIP Lounge Passive Empire",
    category: "Passive Business",
    moneyPerHour: 18500,
    moneyPerHourDisplay: "$18,500 / hour (100% Passive)",
    difficulty: "Easy",
    minInvestment: 2200000,
    minInvestmentDisplay: "$2,200,000 (Property acquisition)",
    timeToPayout: "Continuous daily safe collection ($444,000 / day)",
    soloFriendly: true,
    coopRecommended: false,
    riskTolerance: "Low",
    requiredLevel: "Veteran",
    requirements: ["Own The Malibú Nightclub", "Perform 1 popularity promotion mission every 3 in-game days"],
    strategySteps: [
      "Purchase the VIP Champagne Bar and Sound System upgrades first.",
      "Switch resident DJs when popularity drops below 85% to immediately restore 100% hype.",
      "Empty the office wall safe every 3 playing hours to avoid overflow limits.",
      "Zero police raid risk when security staff upgrade is equipped.",
    ],
    whyRecommended: "Zero risk, completely passive revenue stream that compounds while you explore the map or complete story missions.",
    confidence: "CONFIRMED",
    source: "Trailer 1 Nightlife Systems",
  },
  {
    id: "method-chopshop",
    title: "Exotic Vehicle Boosting & Salvage",
    category: "Street Smuggling",
    moneyPerHour: 120000,
    moneyPerHourDisplay: "$90,000 – $140,000 / hour",
    difficulty: "Medium",
    minInvestment: 850000,
    minInvestmentDisplay: "$850,000 (Chop Shop Garage)",
    timeToPayout: "10–15 minutes per vehicle",
    soloFriendly: true,
    coopRecommended: false,
    riskTolerance: "Medium",
    requiredLevel: "Beginner",
    requirements: ["Own Little Haiti Chop Shop", "Tow Truck or Lockpick Kit"],
    strategySteps: [
      "Check the daily Wanted Vehicle Chalkboard outside the garage.",
      "Patrol Ocean Drive valet lanes and Starfish Island for target models.",
      "Use EMP scrambler to disable police tracking transponders before driving into the shop.",
      "Choose 'Strip for Exotic Parts' for 35% higher return than raw export sale.",
    ],
    whyRecommended: "Consistent active gameplay loop with engaging driving and immediate payout on every successful delivery.",
    confidence: "CONFIRMED",
    source: "Trailer 1 Chop Shop Gameplay",
  },
  {
    id: "method-street-races",
    title: "Midnight Drag & Circuit Racing",
    category: "High-Stakes Contract",
    moneyPerHour: 95000,
    moneyPerHourDisplay: "$75,000 – $110,000 / hour",
    difficulty: "Medium",
    minInvestment: 120000,
    minInvestmentDisplay: "$120,000 (Tuned car)",
    timeToPayout: "3–5 minutes per sprint race",
    soloFriendly: true,
    coopRecommended: true,
    riskTolerance: "Medium",
    requiredLevel: "Intermediate",
    requirements: ["Vehicle with 700+ Horsepower", "Meet unlock at 23:00"],
    strategySteps: [
      "Tune your launch tire pressure and install Stage 2 Nitrous.",
      "Race the South Beach Straightaway sprints for quickest round times.",
      "Wager the maximum allowed $10,000 bet against AI rivals.",
      "Maintain clean racing line through the final chicane to trigger win multipliers.",
    ],
    whyRecommended: "Quickest cash loop when you want short bursts of high-intensity racing action with instant cash handoffs.",
    confidence: "REPORTED",
    source: "Street Racing Audio Leaks",
  },
  {
    id: "method-convenience-stores",
    title: "Fast Cash: Convenience Store & Cash Register Chain",
    category: "Street Smuggling",
    moneyPerHour: 45000,
    moneyPerHourDisplay: "$35,000 – $55,000 / hour",
    difficulty: "Easy",
    minInvestment: 4800,
    minInvestmentDisplay: "$4,800 (Pistol + Mask)",
    timeToPayout: "2 minutes per robbery",
    soloFriendly: true,
    coopRecommended: true,
    riskTolerance: "Low",
    requiredLevel: "Beginner",
    requirements: ["Handgun", "Motorbike for rapid escape through alleys"],
    strategySteps: [
      "Target convenience stores situated near highway on-ramps.",
      "Shoot the register to crack it open instantly instead of waiting for clerk animation.",
      "Escape on a Sanchez dirt bike by hopping down beach pedestrian staircases.",
      "Cooldown wanted level in underground stormwater culverts before hitting next store.",
    ],
    whyRecommended: "Best zero-barrier entry method for new players in Chapter 1 with under $10,000 bankroll.",
    confidence: "OFFICIAL",
    source: "Trailer 1 Convenience Store Holdup",
  },
];
