import {
  Bike,
  Camera,
  Car,
  CircleDot,
  CloudSun,
  Crosshair,
  DollarSign,
  Egg,
  Flag,
  Gem,
  LineChart,
  Map as MapIcon,
  Mountain,
  Package,
  Plane,
  Radio,
  Ship,
  Star,
  Tag,
  Target,
  TrendingUp,
  VenetianMask,
  Warehouse,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  car: Car,
  bike: Bike,
  bicycle: Bike,
  boat: Ship,
  heli: Wind,
  plane: Plane,
  target: Target,
  crosshair: Crosshair,
  ramp: Mountain,
  darts: Target,
  dollar: DollarSign,
  mask: VenetianMask,
  flag: Flag,
  chart: LineChart,
  gem: Gem,
  map: MapIcon,
  cloud: CloudSun,
  star: Star,
  ammo: CircleDot,
  zap: Zap,
  tag: Tag,
  warehouse: Warehouse,
  radio: Radio,
  camera: Camera,
  wrench: Wrench,
  egg: Egg,
  package: Package,
  trending: TrendingUp,
};

export function IconByName({ name, className }: { name: string; className?: string }) {
  const Icon = MAP[name] ?? Star;
  return <Icon className={className} />;
}
